### ISSUE TITLE
Data question from NYCT

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#109]
In the table in the definitions section, it lists bus routes 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 and 14 as premium routes.  What are these routes?

**Comment by rickl4** [comment]
I think there was a typo/confusion since the MTA operates commuter railroads and local bus. 

Instead of listing bus routes 1-14 as premium routes, it should be the following:

Metro North Railroad has the following premium routes/train lines: 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14. (All Rail)
LIRR has the following premium routes/train lines: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12. (All Rail)

**Comment by wklumpen** [comment]
Should be updated on the production website.

**Comment by mlbtc** [comment]
The chart already specifies that all MNR rail service and all LIRR rail service is premium. Wouldn't the routes #1-14 for MNR and routes #1-12 for LIRR be redundant and not need to be in the table at all? The phrasing won’t make sense to a public-facing audience, since the railroads don’t refer to their routes by number - so to the extent that premium service can be designated by route names or by the entire service (e.g. LIRR rail) that would be best.
