### ISSUE TITLE
Staten Island Ferry shouldn't be a premium mode

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#130]
New York City Transit caught this bug. The Staten Island Ferry is free.

**Comment by wklumpen** [comment]
### Recommendation: Wontfix (subject to data updates)
We've double-checked and can confirm this is an issue with the data (and not just a documentation issue), however at this point @aakarner and I are suggesting that we leave this issue open as a bug, but classify as a "wontfix" because (a) updating the fare matrices for NYC with a new correct graph is computationally expensive, and (b) we don't feel the impact of the error is particularly large.

### Rationale
Differences in accessibility between "premium" and "non-premium" travel calculations are dependent on the amount of "premium" transit that exists in the area. 
* Trips that use the Staten Island Ferry are primarily between Staten Island and Manhattan, as well as some areas in Brooklyn, which are all served by a flat-fare transit service (premium routes are not as prevalent in NYC as they are in other regions). 
* The missing link during the "non-premium" score calculation would only have been used if they provided a _cheaper_, shorter travel time option between origins that would use them. There are not really any parallel routes for most of the trips that are feasible in 90 minutes that use the ferry.
* This is further reinforced by the fact that the Ferry trip takes up 20-30 minutes of the 90 minute transit journey.

**Comment by mlbtc** [comment]
@wklumpen @aakarner thanks for looking into this. Seems fine to classify this as an unresolved bug for now, because of the cost to fix and the relatively low impact of the error.

I think it would be good to note publicly on the dashboard that the SIF fare is classified erroneously & to explain the magnitude & scale of the effect it has on the data. Maybe this could go in the methodology?

**Comment by mlbtc** [comment]
Sounds good, the data note should be posted on the "How it works" page and on the NYC Story page
