### ISSUE TITLE
Update definition of equity neighborhoods [0h]

### ISSUE THREAD

**Issue by dana-rg** [wklumpen/equity-pulse-web#143]
The maps page defines the four region types under the dropdown options but the "equity neighborhoods" definition seems off. Suggest updating to something like: "Equity neighborhoods" are areas that were identified by transit advocates as a priority for transit investment due to past disinvestment or marginalization."

The full definition from the tech documentation was "Areas that local transit advocates and TransitCenter identified as meriting additional resources for transit improvements because of past disinvestments or marginalization in planning decisions." 

The "How it works" page didn't define them since it was on the maps page, so if the full definition is needed it could go here, perhaps under the "equity indicators" section.

**Comment by dana-rg** [comment]
@mlbtc what do you think?

**Comment by mlbtc** [comment]
Sure - maybe to save words: "equity neighborhoods" are priorities for transit investment due to past disinvestment, according to advocates.

I think we could add the regional definitions from the longer methodology to the How It Works page - under the equity indicators section makes sense.

**Comment by wklumpen** [comment]
If you could summarize what text you want me to remove or update I'll catch it in the next pass

**Comment by mlbtc** [comment]
On the Customize this Map tab, under the dropdown for Region, Change the last sentence to: 
Advocates identified "equity neighborhoods" as a priority for transit investment due to past disinvestment or marginalization.

**Comment by mlbtc** [comment]
On the How It Works page, beneath the paragraph starting with "Equity indicators shown on the Story pages..." add another paragraph:

For each region, accessibility and transit service intensity scores are computed for the entire region and then summarized for four analysis boundaries. The Metropolitan statistical area (MSA) consists of a high-density urban center and its suburbs, and is defined by the U.S. Census Bureau. TransitCenter defined the Economic Region as the high-density urban center plus surrounding counties that meet at least one of these criteria: where at least 3% of the people who work in the central city live; where at least 3% of the people who work in the MSA live; where at least 3% of residents of the central city work; or where at least 3% of residents of the MSA work. The Urban Core is a contiguous area with the region's highest existing transit use and/or potential for transit use. TransitCenter defined this area based on: workflow to and from the central city, population density, household incomes, race and ethnicity, and presence of high-frequency transit. Local transit advocates gave input on the definitions. Equity Neighborhoods are areas that local transit advocates identified as meriting additional resources for transit improvements because of past disinvestments or marginalization in planning decisions.

**Comment by wklumpen** [comment]
Will be reflected in the next push to the live database.
