### ISSUE TITLE
incorporate gravity measures in the downloads

### ISSUE THREAD

**Issue by dana-rg** [wklumpen/equity-pulse-web#36]
Gravity measures don't show up in the downloads (in download all by date *I Think*, and not in the regional summaries either), or in the score key descriptions.  

Draft text describing them if you want it: ..."A gravity-based accessibility measure that uses a continuous decay function to weight opportunities based on how quickly they can be reached." [if we the decay parameter that might be enough, and maybe a reference to gravity measures or a formula).

**Comment by wklumpen** [comment]
Gravity measures are included in the Access and Transit Scores section (All scores for a given date), but they are *not* included in the summary scores as they are not part of the Story page. In fact, only the measures used in the Story page are included in the summaries (to make querying faster). 

The gravity measures use the parameter `nexp`, and do appear as a column.

I have also updated the query for this so that the data downloads faster (though it's still relatively slow)

**Comment by dana-rg** [comment]
Ahh -- I see them now that I'm looking for `nexp.`  That should be added to the score key description on the data download page, and then I think this is set.

**Comment by wklumpen** [comment]
I added the paragraph below as an additional note, @dana-rg feel free to re-open if it needs some updating.

Note: An additional gravity-based accessibility score is included for access to jobs, both low-income and all. A gravity-based accessibility measure that uses a continuous decay function to weight opportunities based on how quickly they can be reached. These scores are represented with the parameter `nexp`. These scores are not included in the summary data as they are not used in the story page.
