### ISSUE TITLE
Chicago fare data

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#82]
Chicago advocates thought that access to jobs via low-cost transit only seemed too high (compared to access by all jobs). Is there a way to double check that the Chicago fare-constrained data is correct?

To provide more context on the suspicion, in Chicago, access to jobs with low-cost fares only is at 85% of access to all jobs. Other regions with sizable regional rail systems are at 68% access (Boston), 58% (NYC), 77% (DC)

**Comment by dana-rg** [comment]
I looked at the fare assumptions for Chicago, Boston, DC, and NYC.  Each have costly rail options. It may be that NYC's ratio is so low because its so large that rail really takes you to more jobs. Boston has several premium services that serve a small area so that may have a similar effect of creating greater access with high fare. The Metra in Chicago (which is costly) overlaps with the CTA in the most central areas so there's a clear alternative in some parts, but it is costly on the edges. 

It's hard to tell if these differences are enough to cause these levels but I don't see any red flags.

@diluisi do you have additional insight?

**Comment by aakarner** [comment]
From @diluisi: 

> In Chicago we are considering four agencies (CTA, Metra, PACE Bus, and Northern Indiana Commuter Transportation District). In the list considered Premium, we banned Metra and Northern Indiana Commuter Transportation District. I believe that what happened in this case is that the trips generated before banning the agencies, for the most part, were already performed by the agencies that remained on the low-cost list.
> 
> Perhaps the OTP generated very similar trips in the Chicago area. Which probably did not happen in other regions because the ban had an effect on the choice of travel by OTP.

It also seems like the most expensive Metra trips take a long time to reach locations inside the loop where they'd really boost jobs access (i.e. they're greater than 60 minutes). When we apply the fare restriction, access scores for Aurora and Naperville (at the end of the Metra line) don't change much, but that's because the jobs in downtown Chicago are not accessible within 60 minutes even without a fare restriction.

**Comment by mlbtc** [comment]
That makes sense to me. Thank you for the explanation! I can share with the Chicago folks who asked.
